services:
  - type: web
    name: agfit-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: agfit-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://yourusername.github.io
    healthCheckPath: /
    
databases:
  - name: agfit-mongodb
    databaseName: agfit
    user: agfit-user
    plan: free
